### ISSUE TITLE
[GitHub] GET issues

### ISSUE THREAD

**Issue by jdw6359** [TeamMartinez/YOLO-api#19]
Expose an endpoint responsible for reaching out to GitHub (using the token and secret maintained by api) and returning a collection of issues. 

Need to research the GitHub api and investigate what resources they expose

**Comment by jonobrien** [comment]
[v3 issues docs](https://developer.github.com/v3/issues/)

[GET /orgs/TeamMartinez/repos](https://api.github.com/orgs/TeamMartinez/repos)
[GET /repos/TeamMartinez/YOLO-api/issues](https://api.github.com/repos/TeamMartinez/YOLO-api/issues)

**Comment by jonobrien** [comment]
single endpoint on backend client can query for all issues from the team repos and we can return the json of all the issues from two requests.

then query backend for info on a specfic issue and we return more info about that single.

**Comment by jonobrien** [comment]
@jdw6359 determined no point in making same interface twice since calls would end up being the same.
