### ISSUE TITLE
[GitHub] POST Issues

### ISSUE THREAD

**Issue by jdw6359** [TeamMartinez/YOLO-api#20]
Expose an endpoint responsible for reaching out to GitHub (using the token and secret maintained by api) and creating an issue within GitHub.

Need to research the GitHub api and investigate what resources they expose.

Question: How do we determine what project this issue is specific to?

**Comment by jonobrien** [comment]
Are we using the newest version of the github api with oauth? 
[v3](https://developer.github.com/v3/versions/)  I don't see any reference to the particular version in the omniauth commits.

There would be a difference in endpoints you could query for from their end/different names, etc.

**Comment by jonobrien** [comment]
[post create issue](https://developer.github.com/v3/issues/#create-an-issue)
[edit](https://developer.github.com/v3/issues/#edit-an-issue)

if we are doing comments too:
[post create comment](https://developer.github.com/v3/issues/comments/#create-a-comment)
[edit](https://developer.github.com/v3/issues/comments/#edit-a-comment)

**Comment by jonobrien** [comment]
closing for demo
