### ISSUE TITLE
Add Login Cookie

### ISSUE THREAD

**Issue by vuzDylan** [TeamMartinez/YOLO-api#21]
Please add a cookie with information {auth: true} if the current user is authed or {auth: false} if I am not

**Comment by jdw6359** [comment]
Can you provide more information about how I will be providing this cookie to you?

I am having trouble understanding how I will be returning this cookie in addition to the responses I would typically give you. 

If you are expecting a single endpoint, that may be easier to build.
I think that GET @ /api/verify_authentication would be a good place to start. 

Remember that any request after the initial page load will return a 403 if the user is not authorized, in which case you would be able to handle by making the redirect yourself.
