### ISSUE TITLE
MySQL Database Connection in Production

### ISSUE THREAD

**Issue by jdw6359** [TeamMartinez/YOLO-api#32]
- Install MySQL server on production
- Create db
- Include mysql2 dependency for production group 
  *\* if not in production group, will break if libmysql-client is not installed locally
- Alter connection string for production environment

**Comment by jonobrien** [comment]
#30 see PR for basic command

**Comment by jdw6359** [comment]
Plan to spin up MySQL db instance with AWS and use that in our production environment
