### ISSUE TITLE
Web socket server for chat

### ISSUE THREAD

**Issue by vuzDylan** [TeamMartinez/YOLO-api#34]

**Comment by jonobrien** [comment]
totally don't see chat on the description anymore, unless I missed it.

http://www.se.rit.edu/~swen-344/projects/projectdescription.html#R2

**Comment by vuzDylan** [comment]
My bad I assumed it was still there... welp that is boring

**Comment by jonobrien** [comment]
weird, he never said he was removing it. :+1:

**Comment by jonobrien** [comment]
![proofnochat2](https://cloud.githubusercontent.com/assets/5603941/14970570/2e93d79e-1098-11e6-9638-81084ae0ce95.png)

proof because why not?
