### ISSUE TITLE
Create endpoint for getting stocks that user has pinned to dashboard/bought sold recently

### ISSUE THREAD

**Issue by vuzDylan** [TeamMartinez/YOLO-api#35]

**Comment by jdw6359** [comment]
can you be more specific with the spec here? I am already giving you a list of transactions associated with the user, (so you can handle determining which ones are recent / old). As for the "pinned" stocks, is this simply "favoriting" a stock? I.E. client will make a request to api to favorite a particular stock, and to remove the favorite?

**Comment by vuzDylan** [comment]
We actually just need to know which stocks you own the most of according to krutz

**Comment by jdw6359** [comment]
just `GET @ /stock_transactions`
