### ISSUE TITLE
user needs money

### ISSUE THREAD

**Issue by jonobrien** [TeamMartinez/YOLO-api#37]
'5-10k starting'

**Comment by jdw6359** [comment]
you want the users to have a 'money' attribute and seed it to start?

**Comment by jonobrien** [comment]
ohp :+1:

**Comment by jdw6359** [comment]
I assume that when a request to purchase / sell a stock comes through, I will update the amount of money that a person has?

**Comment by jonobrien** [comment]
@vuzDylan @kocsenc i would say yes

**Comment by kocsenc** [comment]
Make safe assumptions. And document it as if we were to consume the api and we didn't know you
