### ISSUE TITLE
Download Stock Transaction History

### ISSUE THREAD

**Issue by jdw6359** [TeamMartinez/YOLO-api#7]
Write stock transaction history of authenticated user to file

**Comment by jdw6359** [comment]
Endpoint:
GET  /api/stock_transactions/download created
Generate stock transaction .txt, in /public directory and returns path.

Client should be able to use path to download contents of .txt

Format:
:type, :abbreviation, :name, :market_value
![stock_history](https://cloud.githubusercontent.com/assets/2166402/13199305/f37dd42e-d7ef-11e5-85df-a9af699fd603.png)

**Comment by kocsenc** [comment]
Jeez; Also fun fact, my dad used to work for Barrick Gold Corp

**Comment by jdw6359** [comment]
I just grabbed those names off of a list of stocks haha

**Comment by jdw6359** [comment]
@kocsenc also this is a nice solution to "downloading" the history, but I will have a harder time with "uploading" a file to the backend -- not exactly sure how to do that.

**Comment by kocsenc** [comment]
@jdw6359 Actually; I did this over the summer. think about it as data that comes over as an input field in a form. Ezpz.
